openers = {
1:'My mom told me not to talk to strangers online, but I’ll make an exception for you.', 
2: 'Has anyone ever told you...you have Lord Farquaads eyes', 
3: 'If you are any good at math, can you tell me what is sinQ/cosQ?', 
4: 'Cheesy chat-up line, gif war or blind date?', 
5: 'I usually go for 8’s but I guess I’ll settle for a 10.', 
6: 'Tell me, what can I say to impress you?', 
7: 'I guess the pandemic is far from over because your smile is contagious.', 
8: 'Titanic. That’s my icebreaker. What’s up?', 
9: 'Im not looking for that whole one night thing... maybe just like 3 minutes. MAX', 
10: 'I suppose I have to say something nice now?', 
11: 'Hey, you could be my cute girl next door.', 
12: 'I’m tired of Tinder for today … or are you nice?', 
13: 'If you could invent a pizza with four ingredients, what would it be?', 
14: 'Which of your photos do you think I like best?', 
15: 'Do you prefer ten thousand $$$ in cash or in the bank?', 
16: 'Is this really you? I honestly thought it would be harder to find my soulmate on Tinder', 
17: 'Greetings COVID survivor', 
18: 'Peek-a-boo baby girl', 
19: 'What is the opposite of mentoes? ....', 
20: 'Can you tell me your mothers maiden name :)? ', 
21: 'Kowalski status report!', 
22: 'Are you made of copper and tellurium? Because you’re CuTe', 
23: 'Can I have your picture so I can show Santa what I want for Christmas?', 
24: 'Are you a carbon sample? Because I want to date you — drinks this week?', 
25: 'Hey gorgeous, will you be my Tinderella?', 
26: 'Are you the square root of 1? Because you seriously can’t be real!', 
27: 'Hello* pretends to be a waiter* – Here’s your icebreaker garnished with awkwardness.', 
28: 'You’re so gorgeous that you made me forget my good pickup line.', 
29: 'Are you a bank loan? Because you have my interest.', 
30: 'Not much of a bio, you mind if I lightening round you a couple questions'
}
